### ISSUE TITLE
GitHub actions for ci

### ISSUE THREAD

**Issue by kapilt** [cloud-custodian/cel-python#3]
let's get some ci running

**Comment by slott56** [comment]
I think these are the priorities:

 * [https://requires.io/github/web-hook/] (push)
 * [https://source.cloud.google.com/watch/github/webhook/...] (all events)
 * [https://notify.travis-ci.org/] (create, delete, issue_comment, member, public, pull_request, push, and repository)

These are used by Custodian, but don't really seem relevant for CEL, since it's not as visible as Custodian.

 * [https://hooks.slack.com/services] (issues and push)
 * [https://ci.cloudcustodian.io/hook] (deployment, pull_request, and push)
 * [https://webhooks.gitter.im] (all events)

These are also used by Custodian, but don't seem relevant because CEL is more properly a library than an application.

 * [https://cloud.docker.com/api/build/v1/vcs...] (pull_request and push)
 * [https://e9geadujob.execute-api.us-east-1.amazonaws.com/api/manual-webhook] (check_run, check_suite, fork, meta, pull_request, push, release, and status)

**Comment by slott56** [comment]
Commit 4ed7178 seems to have properly activated Travis CI and requirements checking, closing this issue.

**Comment by kapilt** [comment]
travis is doa upstream, this should be moved to GitHub actions

**Comment by kapilt** [comment]
we also want black formatting and precheck tests

**Comment by kapilt** [comment]
travis also appears to not be configured correctly since its not actually posting back to pull requests about success/failure.

**Comment by kapilt** [comment]
travis-ci.org is going to stop working at the end of 2020
