### ISSUE TITLE
Support for Python 3.6 and loose dependencies -> 0.1.2.1 version

### ISSUE THREAD

**Issue by mcharrel** [cloud-custodian/cel-python#32]
👋  I'd like to use this library for a program that runs on Python 3.6. Version `0.1.2` works but the fixed dependencies in the requirements are conflicting with my other dependencies.

Out of curiosity, what were the reasons (outside EOL in 2022) to exclude Python 3.6 starting from `0.1.3` ? 

Would it be possible to publish a version (e.g `0.1.2.1`) on Pypi with Python 3.6 and loose dependencies ? 
[Compare changes](https://github.com/cloud-custodian/cel-python/compare/f6051df99010682ffb68d4d30bf8da832d210aa2...chartinmarrel:mc/0.1.2.1)

**Comment by slott56** [comment]
Feel free to relax the requirements and make a PR with the change. 

It would be best to pin the exact versions you need, rather than permit an open-ended requirement that could break in the future.

**Comment by slott56** [comment]
Sorry for not touching on this earlier: "...what were the reasons (outside EOL in 2022) to exclude Python 3.6 starting from 0.1.3 ?"

The reason was explicitly EOL. It's too difficult to support things past EOL.

**Comment by slott56** [comment]
"After the merge, from this branch, a 0.1.2.1 release would need to be uploaded to pypi."

This release would have to be clearly marked as existing only to provide Python 3.6 support, with a caveat that Python 3.6 is past EOL. It is very likely to get orphaned.

Also. It seems like Commit  7170428795c0e1bce5ea7d287771059669159a84  might be more relevant, since it's the change to `requirements.txt`.

**Comment by kapilt** [comment]
3.6 is end of life dec 2021 not 2022.. aka a few weeks out.

**Comment by slott56** [comment]
At this point, this seems to have been overtaken by events. (I have been bad at keeping up.) 

At this point 3.8 is the oldest to be supported.
